services:
    db:
      image: mysql:8.0.28
      environment:
        MYSQL_ROOT_PASSWORD: user@service
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 5s
        retries: 3
        interval: 10s
      deploy:
        resources:
          limits:
            memory: 512M
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  db-data:


